# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 01:08
from __future__ import unicode_literals

from django.db import migrations, models
from blog.models import Post


def slugify_all_posts(*args):
    for post in Post.objects.all():
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.RunPython(slugify_all_posts)
    ]
